# Site settings
title: Abiola Olatunbosun
description: Portfolio Website
baseurl: "/Portfolio/" # the subpath of your site, e.g. /blog
url: "https://bosunolaide.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abiola Olatunbosun
user_description: A Data Scientist and Machine Learning Engineer, who enjoys working with organizations, to make data-informed decisions, by using data to derive actionable insights, make meaningful predictions, and build cutting-edge products, with contemporary data and programming skills.

user_title: Data Scientist | Machine Learning Engineer
email: abiolaolatunbosun05@gmail.com
twitter_username: bosunolaide
github_username:  bosunolaide
gplus_username:  #

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
