# Site settings
title: Abiola Olatunbosun
description: Portfolio Website
baseurl: "/Portfolio/" # the subpath of your site, e.g. /blog
url: "https://bosunolaide.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abiola Olatunbosun
user_description: A tech professional who combines contemporary Machine Learning and Software Engineering techniques, to build cutting-edge AI powered software products.  
user_title: Machine Learning Engineer
email: olaide_abiola87@yahoo.com
twitter_username: lorem_ipsum
github_username:  bosunolaide
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
